---
- name: Update package cache
  ansible.builtin.apt:
    update_cache: yes

- name: Generate locales
  ansible.builtin.command:
    cmd: locale-gen
  register: locale_gen
  changed_when: locale_gen.rc == 0
...
