---
name: CI
on: [ push ]


concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  yamllint:
    name: YAML Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip3 install yamllint
      - run: yamllint .
  j2lint:
    name: Jinja2 Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip3 install j2lint
      - run: j2lint . --ignore jinja-statements-indentation
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip3 install ansible ansible-lint
      - run: ansible-lint *
...
